#!/bin/sh
[ "$ACTION" = "ifup" ] && [ "$INTERFACE" = "lan" ] && {
    if [ -x /usr/sbin/ipaccount ]; then
        ipaddr=$(uci get network.lan.ipaddr)
#        netmask=$(uci get network.lan.netmask)
        netmask="255.255.254.0"
        /usr/sbin/ipaccount -S -n lan -N "$ipaddr/$netmask"
    fi
    . /lib/functions/network.sh
    network_get_device ifname lan
    ubus call trafficd  setlan '{"dev":"'$ifname'"}'

}

[ "$ACTION" = "ifup" ] && [ "$INTERFACE" = "wan" ] && {
    . /lib/functions/network.sh
    network_get_device ifname wan
    ubus call trafficd  setwan '{"dev":"'$ifname'"}'
}

[ "$INTERFACE" = "lan"] && {
    ubus call trafficd reload
}

[ "$INTERFACE" = "guest" ] && {
    ubus call trafficd reload
}

[ "$ACTION" = "ifup" ] && {
    /usr/sbin/ipaccount -r
}
